### PR TITLE
Write out netCDF files with attributes complete

### PR DESCRIPTION
**Pull request by ddasilva**
This finished some code to write out a sample netCDF4 file driven by the metadata manager class. The netCDF4 files look good; see output from the "ncdump" command below.

image

### CODE REVIEW

**Comment by starfleetjames** [comment]
Looking good to me! And thanks for the ncdump example, that's exactly what I was going to do. Few comments questions: 

* the ncdump was just for a small random image you made I'm assuming? 
* can you ensure that the environment and requirements files now grab the version of netCDF4 that's been working and delete the h5netcdf from it? 

That's all I've got!

**Comment by ddasilva** [comment]
> the ncdump was just for a small random image you made I'm assuming?

exactly. it's a 16x16 image of random numbers.

> can you ensure that the environment and requirements files now grab the version of netCDF4 that's been working and delete the h5netcdf from it?

done

**Comment by ddasilva** [comment]
Hold off on merging, realized tests need to be fixed

**Comment by ddasilva** [comment]
All good to merge at your signal!

**Pull request merged**
